#-------------------------------------------------------
#                    CPT DECLARATION
#-------------------------------------------------------
#
# To add a CPT, copy and paste the CPT config below, 
# and replace with the right datas
#
#

#--------------------- Immersions ----------------------
immersions:
  registration:
    labels:
      name: Immersions
      singular_name: Immersion
      add_new: Ajouter une immersion
      add_new_item: Ajouter immersion
      edit_item: Modifier immersion
      new_item: Nouveau
      all_items: Toutes les immersions
      view_item: Voir l'immersion
      search_item: Rechercher une immersion
      not_found: Aucune immersion
      not_fonud_in_trash: Aucune immersion trouvé dans la corbeille
      menu_name: Immersions
    public: true
    publicly_queryable: true
    show_ui: true
    show_in_rest: true
    show_in_menu: true
    query_var: immersions
    rewrite:
      slug: immersion
    capability_type: post
    has_archive: true
    hierarchical: false
    menu_position: 5
    menu_icon: dashicons-airplane
    exclude_from_search: false
    supports: 
      - title
      - editor
      - thumbnail
